// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_10_health_blocks = "CgkImY_qp88FEAIQDg"; // <GPGSID>
        public const string achievement_baby_steps__reach_500_meters = "CgkImY_qp88FEAIQAw"; // <GPGSID>
        public const string achievement_3000_meters = "CgkImY_qp88FEAIQCw"; // <GPGSID>
        public const string achievement_20_health_blocks = "CgkImY_qp88FEAIQDw"; // <GPGSID>
        public const string achievement_4000_meters = "CgkImY_qp88FEAIQDA"; // <GPGSID>
        public const string achievement_meeting_the_millions = "CgkImY_qp88FEAIQBg"; // <GPGSID>
        public const string achievement_2000_meters = "CgkImY_qp88FEAIQBQ"; // <GPGSID>
        public const string achievement_5_health_blocks = "CgkImY_qp88FEAIQDQ"; // <GPGSID>
        public const string achievement_40_health_blocks = "CgkImY_qp88FEAIQEA"; // <GPGSID>
        public const string leaderboard_max_distance = "CgkImY_qp88FEAIQAA"; // <GPGSID>
        public const string achievement_1000_meters = "CgkImY_qp88FEAIQBA"; // <GPGSID>
        public const string leaderboard_total_distance_travelled = "CgkImY_qp88FEAIQCg"; // <GPGSID>
        public const string achievement_5000_meters = "CgkImY_qp88FEAIQEQ"; // <GPGSID>

}

